### ISSUE TITLE
Integra Live crashes with MOTU FastLane

### ISSUE THREAD

**Issue by jamiebullock** [BirminghamConservatoire/IntegraLive#928]
This is a difficult to reproduce bug.

The following steps have reproduced it, but these do not consistently cause a crash...

1. Install MOTU MIDI FastLane driver
2. Plug in FastLane
3. Start Integra Live
4. Create a new project (File -> New Project)

At this point I have made the software crash. 

This crash has been reproduced under the debugger, with the following stack trace:

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x000000010000a4ad
[Switching to process 1085 thread 0x1607]
0x0000000100035a6e in xmlrpc_DECREF (valueP=0x10000a4a9) at xmlrpc_data.c:114
114    valueP->_refcount--;
(gdb) bt
#0  0x0000000100035a6e in xmlrpc_DECREF (valueP=0x10000a4a9) at xmlrpc_data.c:114
#1  0x000000010000f25d in ntg_xmlrpc_get_callback ()
#2  0x000000010000d018 in ntg_server_do_va ()
#3  0x000000010000d872 in ntg_xmlrpc_get ()
#4  0x000000010002817a in callNamedMethod [inlined] () at /usr/local/src/xmlrpc-c-1.31.0/src/registry.c:311
#5  0x000000010002817a in xmlrpc_dispatchCall (envP=0x102cf2ae8, registryP=0x100080940, methodName=0x0, paramArrayP=0x102fec760, callInfoP=0x102cf2d40, resultPP=0x102cf2a90) at registry.c:337
#6  0x000000010002929c in callOneMethod [inlined] () at /usr/local/src/xmlrpc-c-1.31.0/src/system_method.c:80
#7  0x000000010002929c in system_multicall (envP=0x102cf2bc8, paramArrayP=0x17, serverInfo=0x102cf2b30, callInfo=0x102cf2b30) at system_method.c:176
#8  0x000000010002816c in callNamedMethod [inlined] () at /usr/local/src/xmlrpc-c-1.31.0/src/registry.c:306
#9  0x000000010002816c in xmlrpc_dispatchCall (envP=0x102cf2bc8, registryP=0x100080940, methodName=0x1000290d0 "UH??AWAVAUATSH??hH?M?H?U?H??I??H????", paramArrayP=0x102f14740, callInfoP=0x102cf2d40, resultPP=0x102cf2b80) at registry.c:337
#10 0x00000001000282a9 in xmlrpc_registry_process_call2 (envP=0x102cf2ca0, registryP=0x102cf2c30, callXml=0x1033f0a00 "<methodCall>\n  <methodName>system.multicall</methodName>\n  <params>\n    <param>\n      <value>\n        <array>\n          <data>\n", ' ' <repeats 12 times>, "<value>\n", ' ' <repeats 14 times>, "<struct>\n", ' ' <repeats 16 times>, "<member>\n     "..., callXmlLen=30163, callInfo=0x0, responseXmlPP=0x102cf2c30) at registry.c:426
#11 0x0000000100027dd6 in xmlrpc_handleIfXmlrpcReq (handlerArg=0x102f12e20, abyssSessionP=0x102cf2d40, handledP=0x75d3) at abyss_handler.c:562
#12 0x0000000100030605 in runUserHandler [inlined] () at /usr/local/src/xmlrpc-c-1.31.0/lib/abyss/src/server.c:564
#13 0x0000000100030605 in serverFunc (userHandle=0x10000a4a9) at server.c:657
#14 0x000000010002b0e2 in connJob (userHandle=0x10158b200) at conn.c:39
#15 0x0000000100032f3d in pthreadStart (arg=0x1003ae000) at thread_pthread.c:49
#16 0x00007fff8e08f899 in _pthread_body ()
#17 0x00007fff8e08f72a in _pthread_start ()
#18 0x00007fff8e093fc9 in thread_start ()

The bug seems to be related to invalid (non-ascii) characters in the MIDI device list. For example:

![screen shot 2014-01-30 at 16 30 36](https://f.cloud.github.com/assets/579188/2043003/b3203848-89d8-11e3-9b88-3c79039dc59c.png)

A number of other users have also reported "xmlrpc error" relating to MIDI devices, which may be related, e.g. http://integralive.org/forum/discussion/680/akai-lpd8-error#Item_1

**Comment by jamiebullock** [comment]
Given the backend has been completely rewritten and now uses portmidi, *and* I couldn't reproduce this yesterday, I am now closing.
